spring.application.name=mariana

# URL do banco de dados (substitua mariano_db pelo nome real do seu banco)
spring.datasource.url=jdbc:mysql://localhost:3306/mariano_db?serverTimezone=UTC

# Suas credenciais do banco
spring.datasource.username=root
spring.datasource.password=sua_senha_aqui

# Atualiza as tabelas automaticamente baseado no seu código Java
spring.jpa.hibernate.ddl-auto=update